myblog/blog/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from blog.forms import LoginForm

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'register/$', views.register, name='register'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html', 
        'authentication_form': LoginForm},name = 'login'),
    url(r'adminregistration/$', views.adminregistration, name='adminregistration'),
    url(r'dashboard/$', views.dashboard, name='dashboard'),
    url(r'createpost/$', views.createpost, name='createpost'),
    url(r'editpost/(?P<post_id>\d+)$', views.editpost, name='editpost'),
    url(r'deletepost/(?P<post_id>\d+)$', views.deletepost, name='deletepost'),
    url(r'viewpost/(?P<post_id>\d+)$', views.viewpost, name='viewpost'),
    url(r'savecomment/(?P<post_id>\d+)$', views.savecomment, name='savecomment'),
    url(r'get_tags/$', views.get_tags, name='get_tags'),
    url(r'manage_like/$', views.manage_like, name='manage_like'),
    url(r'delete_comment/$', views.delete_comment, name='delete_comment'),
    url(r'home/$', views.home, name='home')
]

myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', views.logout, {'next_page': '/blog/home'})
]

myblog/blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
	title = models.CharField(max_length=200)
	content = models.TextField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	created_at = models.DateTimeField()
	updated_at = models.DateTimeField()
	viewers = models.IntegerField(default=0)
	is_active =  models.BooleanField(default=1)

class Comment(models.Model):
	comment_text = models.TextField()
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	is_like = models.IntegerField(default=0)
	like_count = models.IntegerField(default=0)
	unlike_count = models.IntegerField(default=0)
	created_at = models.DateTimeField()

class Category(models.Model):
	name = models.CharField(max_length=50)

class PostCategory(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)

class UserRole(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	role_id = models.IntegerField(default=2)

class Tags(models.Model):
	name = models.CharField(max_length=50)

class PostTag(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	tag = models.ForeignKey(Tags, on_delete=models.CASCADE)

myblog/blog/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from .models import Category

class RegisterForm(forms.Form):
	username = forms.CharField(label="Username", max_length=30,
		widget=forms.TextInput(attrs={'class' : 'form-control'}))
	email = forms.EmailField(label="Email", max_length=254,
		widget=forms.TextInput(attrs={'class' : 'form-control'}))
	password1 = forms.CharField(label="Password", max_length=30,
	 widget=forms.PasswordInput(attrs={'class' : 'form-control'}))
	password2 = forms.CharField(label="Confirm Password", max_length=30,
	 widget=forms.PasswordInput(attrs={'class' : 'form-control'}))

	def clean(self):
		cleaned_data = super(RegisterForm, self).clean()
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords and confirm password didn't match.")
		return self.cleaned_data

class LoginForm(AuthenticationForm):
	username = forms.CharField(label="MyUsername", max_length=30,
		widget=forms.TextInput(attrs={'class' : 'form-control'}))
	password = forms.CharField(label="Password", max_length=30, 
		widget=forms.PasswordInput(attrs={'class' : 'form-control'}))

class CreatePostForm(forms.Form):
	title = forms.CharField(max_length=200,
		widget=forms.TextInput(attrs={'class' : 'form-control'}))
	content = forms.CharField(
		widget=forms.Textarea(attrs={'class' : 'form-control'}))
	tags = forms.CharField(max_length=200,
		widget=forms.TextInput(attrs={'class' : 'form-control'}))

class CommentForm(forms.Form):
	comment = forms.CharField(max_length=500,
		widget=forms.TextInput(attrs={'class' : 'form-control'}))

myblog/blog/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.db.models import Count
import json
from django.urls import reverse
from blog.forms import *
from .models import UserRole, Post, Category, Tags, PostCategory, PostTag, Comment

@csrf_protect
def register(request):
	
    if request.method == 'POST':
    	form = RegisterForm(request.POST)
    	if form.is_valid():
    		user = User.objects.create_user(
    			username=form.cleaned_data['username'],
    			password=form.cleaned_data['password1'],
    			email=form.cleaned_data['email']

    			)
    		u = UserRole(user=user)
    		u.save()
    		return render(request, 'success.html')
    	else:
    		return render(request, 'register.html',
    			{
    			   'form': form
    			})
        
    else:
    	form = RegisterForm()
    	return render(request, 'register.html', {
		     'form': form
		 })

def adminregistration(request):

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
                email=form.cleaned_data['email']

                )
            u = UserRole(user=user, role_id = 1)
            u.save()
            return render(request, 'success.html',
                {
                 'admin': 1
                })
    else:
        form = RegisterForm()
        return render(request, 'adminregister.html', {
             'form': form
         })

@login_required(login_url="login/")
def dashboard(request):

    user_role = UserRole.objects.filter(user_id = request.user.id)
    role_id = user_role[0].role_id
    post = Post.objects.annotate(Count('comment')).order_by('updated_at')
    return render(request,"dashboard.html",
        {
		 'post': post,
         'role_id': role_id,
         'user_id': request.user.id
		})

def home(request):
        return HttpResponse("hello")

def createpost(request):

    cat =  Category.objects.all().order_by('id')
    if request.method == 'POST':
        form = CreatePostForm(request.POST)
        if form.is_valid():
            cat_id = request.POST.get('category', '')
            tag_names = form.cleaned_data['tags']
            tag_names = tag_names[:-1]
            tag_name_list = tag_names.split(', ')
            tags = Tags.objects.all().order_by('id')
            tag_id_arr = []
            for tags_n in tag_name_list:
                for tag_obj in tags:
                    if tags_n == tag_obj.name:
                        tag_id_arr.append(tag_obj.id)
                        break
            post = Post.objects.create(
                title = form.cleaned_data['title'],
                content = form.cleaned_data['content'],
                created_at = timezone.now(),
                updated_at = timezone.now(),
                user_id = request.user.id
                )
            PostCategory.objects.create(
                post = post,
                category = Category(id = cat_id)

                )
            for tag_id in tag_id_arr:
                PostTag.objects.create(
                    post = post,
                    tag = Tags(id = tag_id)
                    )

            return HttpResponseRedirect(reverse('blog:dashboard'))
        else:
            return render(request, 'createpost.html', {
             'form': form,
             'category': cat
         })

    else:
        form = CreatePostForm()
        return render(request, 'createpost.html', {
             'form': form,
             'category': cat
         })


def get_tags(request):

    if request.is_ajax():
        q = request.GET.get('term', '')
        tags = Tags.objects.filter(name__icontains = q )
        results = []
        for tag in tags:
            tag_json = {}
            tag_json['id'] = tag.id
            tag_json['label'] = tag.name
            tag_json['value'] = tag.name
            results.append(tag_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

def editpost(request, post_id):

    cat =  Category.objects.all().order_by('id')
    if request.method == 'POST':
        form = CreatePostForm(request.POST)
        if form.is_valid():
            cat_id = request.POST.get('category', '')
            tag_names = form.cleaned_data['tags']
            tag_names = tag_names[:-1]
            tag_name_list = tag_names.split(', ')
            tags = Tags.objects.all().order_by('id')
            tag_id_arr = []
            for tags_n in tag_name_list:
                for tag_obj in tags:
                    if tags_n == tag_obj.name:
                        tag_id_arr.append(tag_obj.id)
                        break
            Post.objects.filter(id=post_id).update(
               title=form.cleaned_data['title'],
               content = form.cleaned_data['content'],
               updated_at = timezone.now()
            )
            PostCategory.objects.filter(post_id = post_id).update(
                category = Category(id = cat_id)
                )
            PostTag.objects.filter(post_id = post_id).delete()
            for tag_id in tag_id_arr:
                if tag_id:
                    PostTag.objects.create(
                        post = Post(id=post_id),
                        tag = Tags(id = tag_id)
                    )
        return HttpResponseRedirect(reverse('blog:dashboard'))
    else:
        posts = Post.objects.get(id=post_id)
        posts_cat = PostCategory.objects.get(post_id = post_id)
        posts_tag_id = PostTag.objects.filter(post_id = post_id)
        
        tags = ''
        for pt in posts_tag_id:
            tags += pt.tag.name + ', '
            
        data = {'title': posts.title, 'content': posts.content, 'tags': tags}
        form = CreatePostForm(initial=data)
        return render(request, 'editpost.html', {
             'form': form,
             'category': cat,
             'category_id': posts_cat.category.id,
             'post_id': post_id
         })

def deletepost(request, post_id):

    Post.objects.filter(id=post_id).delete()
    return HttpResponseRedirect(reverse('blog:dashboard'))

def viewpost(request, post_id):

    post_tag = PostTag.objects.filter(post_id = post_id)
    post_cat = PostCategory.objects.filter(post_id = post_id)
    comments = Comment.objects.filter(post_id = post_id)
    user_role = UserRole.objects.filter(user_id = request.user.id)
    role_id = user_role[0].role_id
    viewers = post_cat[0].post.viewers
    viewers += 1
    Post.objects.filter(id = post_id).update(
                viewers = viewers
                )
    tag_name = ''
    for pt in post_tag:
        tag_name += pt.tag.name.title() + ', '
        
    tag_name = tag_name[:-2]
    for pc in post_cat:
        category_name = pc.category.name.title()
        post_title = pc.post.title.title()
        post_content = pc.post.content
        user_name = pc.post.user.username.title()

    comment_form = CommentForm()
    return render(request, 'viewpost.html', {
             'category_name': category_name,
             'post_title': post_title,
             'post_content': post_content,
             'user_name': user_name,
             'tag_name': tag_name,
             'CommentForm': CommentForm,
             'post_id': post_id,
             'comments': comments,
             'role_id': role_id,
             'user_id': request.user.id,
             'post_user_id': post_cat[0].post.user.id
         })

def savecomment(request, post_id):
    user_id =request.user.id
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.cleaned_data['comment']
            Comment.objects.create(
                comment_text = comment,
                post = Post(id = post_id),
                user = User(id = user_id),
                created_at = timezone.now()
                )
        return HttpResponseRedirect(reverse('blog:viewpost', args=[post_id]))

def manage_like(request):

    if request.is_ajax():
        cat_id = request.GET.get('cat_id', '')
        like_val = request.GET.get('like_val', '')
        like_val = int(like_val)
        like_unlike_count = request.GET.get('like_unlike_count', '')
        like_unlike_count = int(like_unlike_count)
        like_unlike_count += 1
        if like_val == 1:
            comments = Comment.objects.filter(id = cat_id ).update(
                is_like = like_val,
                like_count = like_unlike_count
            )
        else:
            comments = Comment.objects.filter(id = cat_id ).update(
                is_like = like_val,
                unlike_count = like_unlike_count
            )
        data = json.dumps(like_unlike_count)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

def delete_comment(request):

    if request.is_ajax():
       cat_id = request.GET.get('cat_id', '')
       Comment.objects.filter(id = cat_id ).delete()
       data = ''
       mimetype = 'application/json'
       return HttpResponse(data, mimetype)

myblog/blog/templates/adminregister.html
{% extends "base.html" %}
{% block title %}User Registration{% endblock %}
{% block content %}
{% if form.errors %}
    {% if form.errors.password2 %}
    	{{ form.errors.password2 }}
    {% endif %}
{% endif %}
<form method="post" action=".">
{% csrf_token %}
    <table border="0">
        {{ form.as_table }}
    </table>
    <input type="submit" value="Register" />
</form>
{% endblock %}

myblog/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog</title>
    <link href="{% static 'myblog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'myblog/css/clean-blog.min.css' %}" rel="stylesheet">
    <link href="{% static 'myblog/vendor/font-awesome/css/font-awesome.min.css' %}" 
    rel="stylesheet" type="text/css">
    <!--<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'> -->
</head>

<body>
    
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="/blog/dashboard">Dashboard</a>
                {% else %}
                    <a class="navbar-brand" href="/blog/home">Home</a>
                {% endif %}
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="/logout">Logout</a>
                    </li>
                    {% else %}
                       <li>
                        <a href="/blog/login">Login</a>
                       </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    

    <header class="intro-header" style="background-image: url({% static 'myblog/img/home-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% block content %}
    
    {% endblock %}
    <hr>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    
                    <p class="copyright text-muted">Copyright &copy; Blog</p>
                </div>
            </div>
        </div>
    </footer>
    <script src="{% static 'myblog/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'myblog/js/clean-blog.min.js' %}"></script>

</body>

</html>

myblog/blog/templates/createpost.html
{% extends "base.html" %}
{% load static %} 
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <form role="form" method="post" action=".">
                    {% csrf_token %}
                          <div class="form-group">
                           <label> Post Title </label>
                                {{ form.title}}
                            </div>
                            <div class="form-group">
                            <label>Post Description </label>
                            {{ form.content}}
                            </div>
                           <div class="form-group">
                               <label>Post category</label>
                                 <select id="id_category" name="category">
                                    <option value="">Select category</option>
                                        {% for cat in category %}
                                    <option value= {{cat.id}}> {{cat.name}}</option>
                                        {% endfor %}
                                    </select>
                            </div>
                            <div class="form-group">
                            <label>Post Tags</label>
                             <div class="ui-widget"> {{ form.tags}}</div>
                        </div>
                    <button type="submit" class="btn btn-primary">Create Post</button>
                </form>
            </div>
        </div>
    </div>
<link rel="stylesheet" href="{% static 'myblog/css/jquery-ui.css' %}"
 type="text/css" media="all" />
<script src="{% static 'myblog/js/jquery.min.js' %}" type="text/javascript">
</script> 
<script src="{% static 'myblog/js/jquery-ui.min.js' %}" 
type="text/javascript"></script>
<script src="{% static 'myblog/js/blog.js' %}"></script>
{% endblock %}

myblog/blog/templates/dashboard.html
{% extends "base.html" %}
welcome home
{% block content %}
<a href="/blog/createpost">Add Post</a>
<div><a href="/logout">Logout</a></div>
<h1>Hello</h1>
<table border="2">
   <tr>
        <th>Post Title</th>
        <th>Total comments</th>
        <th>View</th>
        <th>Post Updated</th>
        <th>Action </th>
   </tr>
   {% for p in post %}
       <tr>
           <td> {{ p.title }}</td>
           <td> {{p.comment__count}} </td>
           <td> {{p.viewers}} </td>
           <td> {{ p.updated_at|date:"d M Y" }} </td>
           <td>
           {% if role_id == 1 or user_id == p.user.id %}
           <a href="/blog/editpost/{{p.id}}">Edit</a>
           <a href="/blog/deletepost/{{p.id}}">Delete</a>
           {% endif %}
           <a href="/blog/viewpost/{{p.id}}">View</a>
           </td>
       </tr>
   {% endfor %}
</table>
{% endblock %}

myblog/blog/templates/editpost.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <form role="form" method="post" action="./{{post_id}}">
                    {% csrf_token %}
                          <div class="form-group">
                           <label> Post Title </label>
                                {{ form.title}}
                            </div>
                            <div class="form-group">
                            <label>Post Description </label>
                            {{ form.content}}
                            </div>
                           <div class="form-group">
                               <label>Post category</label>
                                 <select id="id_category" name="category">
                                <option value="">Select category</option>
                                    {% for cat in category %}
                                <option value= {{cat.id}}
                                    {% if cat.id == category_id %}selected="selected"{% endif %}>
                                        {{cat.name}}</option>
                                         {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                            <label>Post Tags</label>
                             <div class="ui-widget"> {{ form.tags}}</div>
                        </div>
                    <button type="submit" class="btn btn-primary">Update Post</button>
                </form>
            </div>
        </div>
    </div>
<link rel="stylesheet" href="{% static 'myblog/css/jquery-ui.css' %}"
 type="text/css" media="all" />
<script src="{% static 'myblog/js/jquery.min.js' %}" type="text/javascript">
</script> 
<script src="{% static 'myblog/js/jquery-ui.min.js' %}" 
type="text/javascript"></script>
<script src="{% static 'myblog/js/blog.js' %}"></script>
{% endblock %}

myblog/blog/templates/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog</title>
    <link href="{% static 'myblog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'myblog/css/clean-blog.min.css' %}" rel="stylesheet">
    <link href="{% static 'myblog/vendor/font-awesome/css/font-awesome.min.css' %}" 
    rel="stylesheet" type="text/css">
    <!--<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'> -->
</head>

<body>

    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/blog/home">Home</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/blog/login">Login</a>
                    </li>
                    <li>
                        <a href="/blog/register">Sign Up</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <header class="intro-header" style="background-image: url({% static 'myblog/img/home-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            	{% for comment in comments %}
            		{% ifchanged comment.post.title %}
            		<div class="post-preview">
            			<a href="/blog/viewpost/{{comment.post.id}}">
                        <div class="post-title">
                            {{comment.post.title}}
                        </div>
                        </a>
                        <div class="post-subtitle">
                            {{comment.post.content}}
                        </div>
                    	<p class="post-meta">Post updated <a href="#"></a> on 
                    		{{comment.post.updated_at|date:"d M Y" }}</p>
            		</div>
                    <hr>
            		{% endifchanged %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}
    <hr>
	<footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    
                    <p class="copyright text-muted">Copyright &copy; Blog</p>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'myblog/js/jquery.min.js' %}"></script>

    <script src="{% static 'myblog/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'myblog/js/clean-blog.min.js' %}"></script>

</body>

</html>

myblog/blog/templates/login.html
{% extends "base.html" %}
{% block content %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <form role="form" method="post" action=".">
                    {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_table }}
                        </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                </form>
            </div>
        </div>
    </div

{% endblock %}

myblog/blog/templates/register.html
{% extends "base.html" %}
{% block content %}
    {% if form.errors %}
    {% if form.errors.password2 %}
    	{{ form.errors.password2 }}
    {% endif %}
	{% endif %}
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<form role="form" method="post" action=".">
					{% csrf_token %}
						<div class="form-group">
							{{ form.as_table }}
						</div>
					<button type="submit" class="btn btn-primary">Register</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

myblog/blog/templates/success.html
{% extends "base.html" %}
{% block content %}
{% if admin == 1 %}
    Admin Registered Successfully.
    {% else %}
      User registered successfully.
{% endif %}
{% endblock %}

myblog/blog/templates/viewpost.html
<!DOCTYPE html>
<html>
<head>
<title>{{ post_title }}</title>
</head>
<body>
    <a href="/blog/dashboard">Dashboard</a>
    {% load static %}
	<div style="width: 1000px;">
	    <div><a href="/logout">Logout</a></div>
		<h2>{{ post_title }}</h2>
		<br>
		<div>by {{user_name}}</div>
		<div>Category: {{category_name}} | Tag: {{tag_name}}</div>
		<p>{{post_content}}</p>
	</div>
	<h5>Comments</h5>
	{% if comments.count >= 1 %}
	    <ul>
        {% for comment in comments %}
            <div id="comment{{comment.id}}">
            <li>{{comment.comment_text}}</li>
            {% if role_id == 1 or user_id == post_user_id %}
            <input type="button" value="delete" id="delete{{ comment.id }}"
             onclick="deleteComment(this.id)"
             >
             
             {% endif %}
             <input type="hidden" id="hiddenlike{{comment.id}}"
              value="{{comment.like_count}}">
             <input type="button" value="like" id="like{{ comment.id }}"
             onclick="manageCommentLike(this.id)"
             {% if comment.is_like == 1%} hidden="hidden" {% endif %} />
             <input type="hidden" id="hiddenunlike{{comment.id}}"
              value="{{comment.unlike_count}}">
            
            <input type="button" value="Unlike" id="unlike{{ comment.id }}"
             onclick="manageCommentLike(this.id)" 
             {% if comment.is_like == 2 %} hidden="hidden" {% endif %}
             />
             <select id="like_count_select{{comment.id}}" name="like_count_select" 
             onchange="showLikeUnlikeCount(this.value, this.id)">
                 <option value="">Select--</option>
                 <option value="like">like</option>
                 <option value="unlike">unlike</option>
             </select>
             <input type="text" id="liketext{{comment.id}}" value="" placeholder="count">
             </div>

        {% endfor %}
        </ul>
	{% endif %}
	<form method="post" action="../savecomment/{{post_id}}">
	{% csrf_token %}
	<div>{{CommentForm.comment}}
     <input type="submit" value="post" />
	</div>
    
    </form>
    <script src="{% static 'myblog/js/jquery.min.js' %}" type="text/javascript">
</script>
<script src="{% static 'myblog/js/blog-ajax.js' %}"></script>
</body>
</html>